local beautiful = require('beautiful');
local xrdb = beautiful.xresources.get_current_theme();

local config = {
    global = {
        m = 10,
        r = 7,

    },
    fonts = {
        is = "Material Design Icons Desktop 12",
        im = "Material Design Icons Desktop 14",
        tll = "SF Pro Display Light 12",
        tlb = "SF Pro Display Semibold 12",
        tmb = "SF Pro Display Semibold 10",
        m = "Operator Mono Lig",
        t = "SF Pro Rounded",
    },
    icons = {
        arch = '󰣇',
        date = '󰸘',
        time = '󰅐',
        power = '󰐥',
        vol_mute = '󰝟',
        vol_1 = '󰕿',
        vol_2 = '󰖀',
        vol_3 = '󰕾',
        wifi = '󰖩',
        wifix = '󰖪',
        bt = '󰂯',
        btx = '󰂲',
        pac = '󰏗',
        mem = '󰍛',
        lan = '󰲝',
        lanx = '󰲜',
        note = '󰀠',
        restart = '󰜉',
        logout = '󰗽',
        suspend = '󰤄',
        bat10 = '󰁺',
        bat20 = '󰁻',
        bat30 = '󰁼',
        bat40 = '󰁽',
        bat50 = '󰁾',
        bat60 = '󰁿',
        bat70 = '󰂀',
        bat80 = '󰂁',
        bat90 = '󰂂',
        bat = '󰁹',
    },
    colors = {
        b = '#333538',
        t = '#00000000',
        w = '#fefefe',
        f = '#C9DDFC80',
        xf = xrdb.foreground,
        xb = xrdb.background,
        x0 = xrdb.color0,
        x1 = xrdb.color1,
        x2 = xrdb.color2,
        x3 = xrdb.color3,
        x4 = xrdb.color4,
        x5 = xrdb.color5,
        x6 = xrdb.color6,
        x7 = xrdb.color7,
        x8 = xrdb.color8,
        x9 = xrdb.color9,
        x10 = xrdb.color10,
        x11 = xrdb.color11,
        x12 = xrdb.color12,
        x13 = xrdb.color13,
        x14 = xrdb.color14,
        x15 = xrdb.color15,
    },
    topbar = {
        h = 30,
        w = 30,
        dw = 200,
        sw = 200,
        utilities = {
            wifi = true,
            bt = true,
            lan = false,
            vol = true,
            bat = true,
            pac = true,
            mem = true,
            note = false,
        },
    },
    tagswitcher= {
        h = 120,
    },
    commands = {
        terminal = 'urxvt',
        files = 'nautilus',
        browser = 'chrome',
        rofi = "rofi -show drun -theme global",
        rofi2 = "rofi -show drun -theme launcher"
    }
};

return config;